<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <LangVersion>9</LangVersion>
        <Nullable>enable</Nullable>
        <Title>Guard Clauses</Title>
        <Description>Lightweight guard clause pattern for defensive programming.</Description>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
    </PropertyGroup>

</Project>
